### ISSUE TITLE
[FR] Екстеншънът може да се портне директно към Firefox без промени

### ISSUE THREAD

**Issue by rxshion** [mitko8009/ShkoloTweaks#13]

**Comment by mitko8009** [comment]
Ако знаеш как да го портнеш към Firefox ми пиши по дискорд

**Comment by rxshion** [comment]
Направих го като .zip файл готов за качване в Firefox[shkolotweaks_beta_-0.4.9.zip](https://github.com/user-attachments/files/17281299/shkolotweaks_beta_-0.4.9.zip)

**Comment by mitko8009** [comment]
Благодаря ти.
Ако се занимаваш с js, можеш да се присъединиш към "отбора". Че нямам особено време за **shkolotweaks** напоследък.
