### ISSUE TITLE
[BUG] z-indexing tooltips in popup

### ISSUE THREAD

**Issue by mitko8009** [mitko8009/ShkoloTweaks#8]

**Comment by Crea7orX** [comment]
Solved with [87a64b4](https://github.com/mitko8009/ShkoloTweaks/commit/87a64b446c75166ececbb34d08654dbf954aef65)!

**Comment by Crea7orX** [comment]
Solved with [87a64b4](https://github.com/mitko8009/ShkoloTweaks/commit/87a64b446c75166ececbb34d08654dbf954aef65)!
